### ISSUE TITLE
How to get the Bounding box data from gazebo?

### ISSUE THREAD

**Issue by yellowjs0304** [JenniferBuehler/gazebo-pkgs#19]
Hello, I'm new to Gazebo and Ros so help me please.

I did your pkgs tutorials(Object information and recognition tutorial). 
But when I did this command,
`rosrun gazebo_state_plugins gazebo_request_object_info cube1`
I only got the position and orientation data from cube.

I want to get the bounding box data from cube, Jaco and table.
How to get this data? I can't find it :'(

**Comment by JenniferBuehler** [comment]
Hello, yes the "object information service" gives you the poses of the cube, because it's an object maintained in the information service, like the name suggests ;) the robot and environment are a different thing, from the object management perspective.

You could get the Bounding Box from Gazebo, but that involves a bit of work (programming)... you could subscribe to the gazebo message topic and receive updates from the model as it moves around, then compute the bounding box... but the easier solution would probably be to just write a gazebo plugin which publishes the information you require. You could use the gazebo_state_plugins GazeboObjectInfo as a a template for your code, see function [createBoundingBoxObject()](https://github.com/JenniferBuehler/gazebo-pkgs/blob/f4700ea772e4757ed6a0ebffb50a288dd131dcf4/gazebo_state_plugins/src/GazeboObjectInfo.cpp#L169) (and from where it is called) as a starting point. You'd have to do a similar plugin which computes bounding boxes for all objects you need.

A bit of a "hack" would be to actually add the cube, Jaco and table as "objects" to the object information service. I haven't tried this with mobile objects like the Jaco, where the bounding box changes over time. I'd have to look at the code again to see if it would work (it's been a while I've used this package myself) ;)

All of it requires a bit of software development tinkering, but as a ROS beginner you'll probably be keen to get a bit more into the coding part of it anyway? :)

Sorry I can't be of more help, I haven't implemented a service like this to provide bounding boxes for any object in the world. It's just for the registered objects.

**Comment by yellowjs0304** [comment]
@JenniferBuehler  ThankYou. 
I have another question about object information 
`rosrun gazebo_state_plugins gazebo_request_object_info cube1` from this command 

It returns 
```
object: 
  header: 
    seq: 0
    stamp: 49.451000000
    frame_id: world
  name: cube2
  type: 
    key: 
    db: 
  primitives[]
    primitives[0]: 
        type: 1
      dimensions[]
        dimensions[0]: 0.05
        dimensions[1]: 0.05
        dimensions[2]: 0.05
  primitive_poses[]
    primitive_poses[0]: 
        position: 
        x: 0.199999
        y: -1.62822e-06
        z: 0.755573
      orientation: 
        x: 3.90062e-05
        y: -9.39239e-06
        z: 1.70555e-05
        w: 1
  meshes[]
  mesh_poses[]
  planes[]
  plane_poses[]
  primitive_origin: -1
  mesh_origin: -2
  origin: 
    position: 
      x: 0.199999
      y: -1.62822e-06
      z: 0.755573
    orientation: 
      x: 3.90062e-05
      y: -9.39239e-06
      z: 1.70555e-05
      w: 1
  content: 0
error_code: 0
```
I can't understand the "dimensions[]" meaning.
Would you please explain about this?
